const OK = 'OK';
const INVALID_PROPS = 'INVALID_PROPS';
const INVALID_TOKEN = 'INVALID_TOKEN';
const EXISTING_ACCOUNT = 'EXISTING_ACCOUNT';
const ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND';
const SERVER_ERROR = 'SERVER_ERROR';

const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
const NO_PRODUCT = 'NO_PRODUCT';
const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';
const TOGGLE_PRODUCT_FAILED = 'TOGGLE_PRODUCT_FAILED';
const REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED';

module.exports = {
  OK,
  INVALID_PROPS,
  INVALID_TOKEN,
  EXISTING_ACCOUNT,
  ACCOUNT_NOT_FOUND,
  SERVER_ERROR,
  ADD_PRODUCT_FAILED,
  NO_PRODUCT,
  UPDATE_PRODUCT_FAILED,
  TOGGLE_PRODUCT_FAILED,
  REMOVE_PRODUCT_FAILED
};
