const OK = 'OK';
const INVALID_PROPS = 'INVALID_PROPS';
const EXISTING_ACCOUNT = 'EXISTING_ACCOUNT';
const ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND';
const SERVER_ERROR = 'SERVER_ERROR';

module.exports = {
  OK,
  INVALID_PROPS,
  EXISTING_ACCOUNT,
  ACCOUNT_NOT_FOUND,
  SERVER_ERROR
};
